### ISSUE TITLE
more packages required in prerequisits

### ISSUE THREAD

**Issue by fprimeau** [fprimeau/EARTHSS220#8]

**Comment by fprimeau** [comment]
We should add instructions to add packages for the 
WorldOceanAtlasTools
JLD2
FileIO
so that students can run the P-cycle +O2 model and save the output

**Comment by briochemc** [comment]
Agreed, I’ll add that today. Although I’m inclined to use BSON instead of JLD2 (unmaintained).

**Comment by briochemc** [comment]
Done
